# Generated by Django 5.2.2 on 2025-06-07 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="员工姓名")),
            ],
        ),
        migrations.CreateModel(
            name="TaskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "completed",
                    models.PositiveIntegerField(default=0, verbose_name="完成图片数"),
                ),
                (
                    "errors",
                    models.PositiveIntegerField(default=0, verbose_name="错误图片数"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TaskHelper.employee",
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务记录",
                "verbose_name_plural": "任务记录",
                "unique_together": {("employee", "date")},
            },
        ),
    ]
